// Landlord guides (/landlord-guides) and two free tools (/landlord-tools/rent-increase-calculator,
// /landlord-tools/certificate-due-dates): evergreen pages answering what London landlords search for, each ending in a
// free valuation. Facts are the settled rules (checked October 2026); anything still being confirmed by the government
// is said to be so. General information, not legal advice. Questions at the end of each guide become FAQ structured
// data automatically (siteHeadFor reads <details><summary>…</summary><p>…</p></details>).
module.exports = function (app, opts) {
  const esc = function (v) { return String(v == null ? '' : v).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); };
  const REVIEWED = '2026-10-10', REVIEWED_TXT = 'October 2026';
  const GOV = function (path, text) { return '<a href="https://www.gov.uk/' + path + '" rel="noopener" target="_blank">' + text + '</a>'; };
  const G = [
    { slug: 'letting-agent-fees-london', title: 'How Much Do Letting Agents Charge in London?', h1: 'How much do letting agents charge in London?',
      desc: 'What London letting agents charge landlords: tenant-find, rent collection and full management explained, what should be included and the questions to ask.',
      lead: 'Letting agents in London usually charge landlords a percentage of the rent, and the percentage depends on how much you want the agent to do. Here’s how the levels of service work, what should be included, and how to compare agents properly.',
      body: [
        ['The three levels of service', '<p><b>Tenant find (let only):</b> the agent values the property, markets it, does the viewings, references the tenants, sets up the tenancy and protects the deposit. After move-in, you manage the tenancy yourself.</p><p><b>Rent collection:</b> everything in tenant find, plus the agent collects the rent each month, chases late payments and sends you statements.</p><p><b>Full management:</b> the agent also looks after the property day to day — repairs, safety certificates, inspections, rent reviews, notices and the move-out and deposit return.</p><p>Fees are usually a percentage of the monthly rent plus VAT. Tenant-find fees are often charged up front, while rent collection and management are taken from each month’s rent.</p>'],
        ['What should be included', '<ul><li>A realistic rental valuation based on what similar homes are actually letting for.</li><li>Professional photos and advertising on the main property portals.</li><li>Accompanied viewings and honest feedback.</li><li>Full referencing and Right to Rent checks.</li><li>A compliant tenancy under the Renters’ Rights Act 2025, the government’s information sheet, and deposit protection.</li><li>Clear monthly statements and online access to your account.</li></ul><p>Ask for a written list of what is and isn’t included — extras such as inventories, check-ins and renewals are where costs can creep up.</p>'],
        ['Fees tenants can and can’t pay', '<p>Since the Tenant Fees Act 2019, agents and landlords in England can’t charge tenants for things like referencing or admin. Tenants pay the rent, a refundable deposit (capped at five weeks’ rent where the annual rent is under £50,000), a holding deposit of up to one week’s rent, and a few other permitted payments. See ' + GOV('government/publications/tenant-fees-act-2019-guidance', 'the government’s guidance') + '.</p>'],
        ['Questions to ask any agent', '<ul><li>Are you a member of a Client Money Protection scheme and a government-approved redress scheme? Both are legal requirements for letting agents.</li><li>How long do your homes typically take to let, and how close to the asking rent?</li><li>Who will look after my property day to day?</li><li>How do you handle repairs, and do you mark up contractors’ invoices?</li><li>What happens if the tenant stops paying?</li></ul>'],
        ['How we charge', '<p>We offer all three levels of service across every London borough, with our fees and exactly what’s included set out clearly before you sign. Our money is protected by Client Money Protect, we are ARLA Propertymark protected and members of The Property Ombudsman. <a href="/landlords#services">See our services</a> or <a href="/landlords#valuation">get a free rental valuation</a>.</p>']],
      faq: [['Do letting agent fees include VAT?', 'Usually fees are quoted as a percentage of the rent plus VAT. Always check whether a quote includes VAT.'], ['Is full management worth it?', 'If you live far away, work full time or have more than one property, full management saves time and keeps you compliant with the many rules that apply to landlords.'], ['Can I switch letting agent?', 'Yes. Check your current agent’s notice period and terms first. See our guide to switching letting agent.']] },

    { slug: 'renters-rights-act-landlords', title: 'Renters’ Rights Act 2025: What Landlords Must Do', h1: 'The Renters’ Rights Act 2025: what landlords need to know',
      desc: 'The Renters’ Rights Act changed letting in England from 1 May 2026: periodic tenancies, no section 21, rent increases once a year. What landlords must do now.',
      lead: 'The biggest change to renting in England for decades took effect on 1 May 2026. If you let a property in London, this is what changed and what you need to do.',
      body: [
        ['What changed on 1 May 2026', '<ul><li><b>No more fixed terms:</b> new and existing assured shorthold tenancies became assured periodic (rolling) tenancies. A tenancy agreement can’t have an end date.</li><li><b>Section 21 abolished:</b> you can no longer end a tenancy without a reason. Possession is only possible on the legal grounds — for example selling, moving in, or rent arrears.</li><li><b>Selling or moving in:</b> you can’t use these grounds in the first 12 months of a tenancy.</li><li><b>Rent increases once a year</b> using the formal section 13 notice, which tenants can challenge at the First-tier Tribunal.</li><li><b>No rental bidding:</b> you must advertise at a set rent and can’t accept offers above it.</li><li><b>Rent in advance limited:</b> no more than one month’s rent can be asked for before the tenancy starts.</li><li><b>Pets:</b> tenants can ask to keep a pet and you must not unreasonably refuse.</li><li><b>No discrimination</b> against tenants because they receive benefits or have children.</li></ul>'],
        ['The information sheet', '<p>Landlords had to give every existing tenant the government’s Renters’ Rights Act Information Sheet by 31 May 2026, and must give it to new tenants. Councils can fine landlords up to £7,000 for not doing so. If any of your tenants haven’t had it, give it now — ' + GOV('government/publications/the-renters-rights-act-information-sheet-2026', 'download the official sheet') + '.</p>'],
        ['What’s coming next', '<p>The Act also creates a Private Rented Sector Landlord Database that landlords will have to register on, and a new landlord ombudsman. The government expects these from late 2026 onwards — exact dates are still being confirmed. The Decent Homes Standard and Awaab’s Law (time limits for fixing hazards such as damp and mould) will be applied to private renting later.</p>'],
        ['How we help', '<p>We set every tenancy up correctly, serve the right notices, track rent review dates and keep your certificates and paperwork in order — so you don’t have to follow every change yourself. <a href="/landlords#renters-rights">See how we handle the new rules</a>.</p>']],
      faq: [['Can I still use a fixed-term tenancy?', 'No. Since 1 May 2026 all assured tenancies in England are periodic, with no end date.'], ['How can a tenant end the tenancy?', 'Tenants can end a periodic tenancy by giving notice — usually two months.'], ['Can I evict a tenant to sell?', 'Yes, using the selling ground — but not in the first 12 months of the tenancy, and with the required notice.'], ['Where is the official guidance?', 'The government’s overview for landlords is on GOV.UK: search for “Renters’ Rights Act: an overview for landlords”.']] },

    { slug: 'property-licence-london', title: 'Do I Need a Property Licence in London?', h1: 'Do I need a property licence in London?',
      desc: 'Property licensing in London explained: mandatory HMO, additional and selective licensing, how to check your address, and what happens if you let without one.',
      lead: 'Many London councils require landlords to licence their rented homes, and the rules differ from borough to borough — sometimes street by street. Here’s how licensing works and how to check your property.',
      body: [
        ['The three kinds of licence', '<p><b>Mandatory HMO licence:</b> required everywhere in England for a house or flat let to five or more people who form two or more households and share facilities such as a kitchen or bathroom.</p><p><b>Additional HMO licensing:</b> some councils extend licensing to smaller HMOs — for example three or four sharers.</p><p><b>Selective licensing:</b> some councils require a licence for privately rented homes in certain areas, even a flat let to a single family or couple.</p>'],
        ['How to check your property', '<p>Each council publishes its schemes, which areas they cover and when they end. Use our <a href="/property-checks">free licence checker</a> as a starting point — it gives firm answers for councils we have checked ward by ward — and confirm with the council before you let.</p>'],
        ['What happens without a licence', '<p>Letting a property that needs a licence without one is a criminal offence. Councils can issue civil penalties, and tenants can apply for a rent repayment order to reclaim rent they paid. Licence conditions — such as safety certificates, smoke alarms and room sizes — must also be kept to.</p>'],
        ['We can apply for you', '<p>We prepare and submit licence applications, including the plans and certificates the council asks for. <a href="/licence-application">See our licence application service</a>.</p>']],
      faq: [['How long does a property licence last?', 'Usually up to five years, but many selective schemes end on a fixed date — the council’s scheme page says when.'], ['Does every London borough have selective licensing?', 'No. Schemes vary by council and area, and they change over time, so always check the current scheme for your address.'], ['Who applies — the landlord or the agent?', 'The licence holder is usually the landlord, but an agent can prepare and submit the application.']] },

    { slug: 'landlord-safety-certificates', title: 'Landlord Safety Certificates: Gas, EICR, EPC & Alarms', h1: 'Landlord safety certificates: what you need and when',
      desc: 'The certificates every landlord in England needs: gas safety every year, EICR every five years, an EPC of E or above, and smoke and carbon monoxide alarms.',
      lead: 'Before a tenant moves in, and throughout the tenancy, landlords must have several safety checks in place. Missing one can mean fines and can stop you regaining possession. Here’s the list.',
      body: [
        ['Gas safety certificate — every year', '<p>If the property has gas appliances, a Gas Safe registered engineer must check them every 12 months. Give the tenant a copy of the certificate before they move in and within 28 days of each annual check. <a href="/gas-safety-certificate">Book a gas safety certificate</a>.</p>'],
        ['EICR — at least every five years', '<p>The electrical installation must be inspected and tested by a qualified person at least every five years (or sooner if the report says so). Give the tenant a copy, and fix anything the report says is dangerous or needs investigation. <a href="/eicr">Book an EICR</a>.</p>'],
        ['EPC — rated E or above', '<p>An Energy Performance Certificate is valid for 10 years. You must show it to prospective tenants, and a rented home must normally have a rating of E or above. <a href="/epc">Book an EPC</a> or <a href="/property-checks">check your current rating free</a>.</p>'],
        ['Smoke and carbon monoxide alarms', '<p>You must fit a smoke alarm on every storey used as living accommodation, and a carbon monoxide alarm in any room with a fixed combustion appliance (other than a gas cooker). Check they work on the first day of each new tenancy and repair or replace faulty alarms.</p>'],
        ['Also check', '<ul><li>A legionella risk assessment.</li><li>Furniture and furnishings meet fire safety rules if the home is let furnished.</li><li>The deposit is protected and the required information given within 30 days.</li><li>Right to Rent checks are done before the tenancy starts.</li></ul>']],
      tool: '/landlord-tools/certificate-due-dates',
      faq: [['How often do I need a gas safety certificate?', 'Every 12 months, by a Gas Safe registered engineer.'], ['How long is an EICR valid for a rental?', 'Up to five years, unless the report recommends a sooner inspection.'], ['What EPC rating does a rental need?', 'Normally E or above, unless a valid exemption is registered.']] },

    { slug: 'how-to-raise-the-rent', title: 'How to Raise the Rent: Section 13 Rules for Landlords', h1: 'How to raise the rent under the new rules',
      desc: 'Raising the rent since the Renters’ Rights Act: once a year with a section 13 notice, at least two months’ notice, in line with the market. Free date calculator.',
      lead: 'Since 1 May 2026, the formal section 13 notice is the way to increase the rent on an assured tenancy in England. Here’s how it works — and a free calculator for the earliest date a new rent can start.',
      body: [
        ['The rules', '<ul><li>Rent can be increased <b>once a year</b> — not within 52 weeks of the tenancy starting or of the last increase.</li><li>Use the prescribed <b>section 13 notice</b> (Form 4A) and give at least <b>two months’ notice</b> (six months if rent is paid yearly).</li><li>The new rent should be in line with the <b>open market rent</b> for similar homes.</li><li>The tenant can challenge the increase at the <b>First-tier Tribunal</b>, which decides the market rent — and can’t set it higher than you proposed.</li></ul>'],
        ['Pricing the increase', '<p>Look at what similar homes nearby are letting for now — not what they are advertised at. Our <a href="/landlords#compare">rent comparison</a> and <a href="/london-rents">rents by borough</a> pages show official figures, and we can give you a free valuation based on what we’re actually letting homes for.</p>'],
        ['We’ll do it for you', '<p>For managed landlords we track every rent review date, advise on the right level and prepare and serve the notice.</p>']],
      tool: '/landlord-tools/rent-increase-calculator',
      faq: [['How often can I put the rent up?', 'Once a year, using a section 13 notice.'], ['How much notice do I have to give?', 'At least two months for weekly or monthly rents (six months for yearly).'], ['Can the tenant refuse a rent increase?', 'They can challenge it at the First-tier Tribunal, which will decide the market rent.']] },

    { slug: 'letting-with-pets', title: 'Letting to Tenants With Pets: The New Rules', h1: 'Letting to tenants with pets: the new rules',
      desc: 'Under the Renters’ Rights Act tenants can ask to keep a pet and landlords must not unreasonably refuse. How pet requests work and how to protect your property.',
      lead: 'Since 1 May 2026 tenants in England have the right to ask to keep a pet, and landlords can’t refuse without a good reason. Here’s how requests work.',
      body: [
        ['How a pet request works', '<p>A tenant asks in writing. You must reply in writing within 28 days — you can ask for more information, which gives you a little more time after they reply. You can agree, agree with reasonable conditions, or refuse for a good reason.</p>'],
        ['Reasonable reasons to refuse', '<p>For example, if the lease of a flat forbids pets, or the animal clearly isn’t suitable for the property. A tenant who thinks a refusal is unreasonable can complain and, ultimately, go to court.</p>'],
        ['Protecting your property', '<ul><li>A detailed check-in inventory with photos, so any pet damage is clear at the end.</li><li>The deposit cap still applies — you can’t take a separate pet deposit above the five-week limit.</li><li>Check your landlord insurance covers pet damage.</li></ul>'],
        ['Why it can pay to say yes', '<p>Pet-friendly homes appeal to more tenants, and tenants with pets often stay longer — fewer empty weeks for you.</p>']],
      faq: [['Can I refuse a tenant with a pet?', 'Only with a good reason, such as a lease that forbids pets. You must reply in writing within 28 days.'], ['Can I charge a pet deposit?', 'Not above the normal deposit cap of five weeks’ rent (for annual rents under £50,000).']] },

    { slug: 'section-21-abolished', title: 'Section 21 Abolished: How Landlords End a Tenancy Now', h1: 'Section 21 has gone — how a tenancy ends now',
      desc: 'Section 21 no-fault evictions ended on 1 May 2026. How landlords can now regain possession using section 8 grounds such as selling, moving in or rent arrears.',
      lead: 'Since 1 May 2026 landlords in England can no longer use section 21 to end a tenancy without a reason. Possession is still possible — but only on the legal grounds, with the right notice.',
      body: [
        ['The main grounds for possession', '<ul><li><b>Selling the property</b> — not in the first 12 months of the tenancy.</li><li><b>You or a close family member moving in</b> — not in the first 12 months.</li><li><b>Rent arrears</b> — the amended arrears ground.</li><li><b>Antisocial behaviour</b> and serious breaches of the tenancy.</li></ul><p>Each ground has its own notice period and evidence requirements, and some grounds limit re-letting the property for a period afterwards.</p>'],
        ['Get the paperwork right', '<p>A court will only order possession if the deposit was protected and the right information given, and the notice is valid. Mistakes mean starting again — months later.</p>'],
        ['How tenants end a tenancy', '<p>Tenants can leave by giving notice, usually two months.</p>'],
        ['We’ll guide you', '<p>We advise managed landlords on the right ground, the notice and the evidence needed — and help you plan around the 12-month protected period when you buy, sell or move.</p>']],
      faq: [['Can I still evict a tenant?', 'Yes, using one of the section 8 grounds, such as selling, moving in or rent arrears, with the correct notice.'], ['When did section 21 end?', 'On 1 May 2026, for tenancies in England.']] },

    { slug: 'tenancy-deposit-rules', title: 'Tenancy Deposit Rules for Landlords in England', h1: 'Tenancy deposit rules for landlords',
      desc: 'How much deposit landlords can take (five weeks’ rent), protecting it within 30 days in a government scheme, the information to give, and returning it fairly.',
      lead: 'Getting the deposit right protects you at the end of the tenancy — and getting it wrong can stop you regaining possession. Here are the rules.',
      body: [
        ['How much you can take', '<p>No more than <b>five weeks’ rent</b> where the annual rent is under £50,000, or six weeks’ rent where it’s £50,000 or more. A holding deposit can be no more than one week’s rent.</p>'],
        ['Protect it within 30 days', '<p>Put the deposit in a government-approved tenancy deposit protection scheme and give the tenant the prescribed information within 30 days of receiving it. If you don’t, the tenant can claim compensation and you may not be able to regain possession through the courts.</p>'],
        ['At the end of the tenancy', '<p>Agree any deductions with the tenant, based on the check-in and check-out reports — allowing for fair wear and tear. If you can’t agree, the scheme’s free dispute service decides.</p>'],
        ['We handle it', '<p>We register every deposit, issue the paperwork and handle the return and any dispute, with photo inventories at check-in and check-out.</p>']],
      faq: [['How much deposit can a landlord take?', 'Up to five weeks’ rent if the annual rent is under £50,000.'], ['How long do I have to protect a deposit?', '30 days from receiving it, including giving the tenant the prescribed information.']] }
  ];
  const BY = {}; G.forEach(function (g) { BY[g.slug] = g; });
  const cta = '<section class="ar-cta"><div class="wrap ar-cta-in"><div><h2>Letting a property in London?</h2><p>A free, no-obligation rental valuation from an agent who lets homes in every borough.</p></div><div class="btns"><a class="btn red" href="/landlords#valuation">Free rental valuation →</a><a class="btn line" href="/landlord-guides">More landlord guides</a></div></div></section>';
  const note = '<p class="ar-src">Last checked ' + REVIEWED_TXT + '. This guide is general information for landlords in England, not legal advice — rules change, so check GOV.UK or ask us about your situation.</p>';

  app.get('/landlord-guides', function (req, res) {
    const h = '<section class="ar-hero"><div class="wrap"><p class="ar-kick">Landlord guides</p><h1>Guides for London landlords</h1><p class="ar-lead">Straight answers on fees, the Renters’ Rights Act, licensing, certificates, rent increases and more — kept up to date.</p></div></section>' +
      '<section class="ar-main"><div class="wrap"><ul class="ar-list ar-cover">' + G.map(function (g) { return '<li><a href="/landlord-guides/' + g.slug + '"><b>' + esc(g.h1) + '</b><span>' + esc(g.desc) + '</span></a></li>'; }).join('') + '</ul>' +
      '<h2 style="margin-top:28px">Free landlord tools</h2><ul class="ar-list ar-cover"><li><a href="/landlord-tools/rent-increase-calculator"><b>Rent increase calculator</b><span>The earliest date a new rent can start, and how it compares with local rents.</span></a></li><li><a href="/landlord-tools/certificate-due-dates"><b>Certificate due-date checker</b><span>When your gas safety, EICR and EPC are next due.</span></a></li><li><a href="/landlord-tools"><b>All landlord tools</b><span>Rent comparison, yield and stamp duty calculators, EPC and licence checkers.</span></a></li></ul></div></section>' + cta;
    opts.send(req, res, { name: 'tools', stamp: 'lg1', canon: '/landlord-guides', crumb: 'Landlord guides', title: 'Guides for London Landlords | Residential Realtors', desc: 'Free guides for London landlords: letting agent fees, the Renters’ Rights Act, property licensing, safety certificates, rent increases, pets and deposits.' }, h);
  });
  app.get('/landlord-guides/:slug', function (req, res, next) {
    const g = BY[req.params.slug]; if (!g) return next();
    const others = G.filter(function (x) { return x !== g; }).slice(0, 5);
    const h = '<section class="ar-hero"><div class="wrap"><p class="ar-kick"><a href="/landlord-guides">Landlord guides</a></p><h1>' + esc(g.h1) + '</h1><p class="ar-lead">' + esc(g.lead) + '</p></div></section>' +
      '<section class="ar-main"><div class="wrap mk-art">' + g.body.map(function (s) { return '<h2>' + esc(s[0]) + '</h2>' + s[1]; }).join('') +
      (g.tool ? '<div class="ar-card rv" style="margin:18px 0"><b>Free tool:</b> <a href="' + g.tool + '">' + (g.tool.indexOf('rent') !== -1 ? 'Rent increase calculator — the earliest date a new rent can start →' : 'Certificate due-date checker — when your gas, EICR and EPC are next due →') + '</a></div>' : '') +
      '<div class="sw-faq"><h2>Common questions</h2>' + g.faq.map(function (q) { return '<details><summary>' + esc(q[0]) + '</summary><p>' + esc(q[1]) + '</p></details>'; }).join('') + '</div>' + note +
      '<h2>More guides</h2><ul class="ar-list ar-cover">' + others.map(function (x) { return '<li><a href="/landlord-guides/' + x.slug + '"><b>' + esc(x.h1) + '</b></a></li>'; }).join('') + '</ul></div></section>' + (opts.trackHtml ? opts.trackHtml('') : '') + cta;
    opts.send(req, res, { name: 'tools', stamp: 'lg-' + g.slug + REVIEWED, canon: '/landlord-guides/' + g.slug, crumb: 'Landlord guides', crumbUrl: '/landlord-guides', crumb2: g.h1, title: g.title + ' | Residential Realtors', desc: g.desc,
      ld: [{ '@type': 'Article', headline: g.h1.slice(0, 110), description: g.desc, dateModified: REVIEWED, datePublished: REVIEWED, author: { '@type': 'Organization', name: 'Residential Realtors' }, publisher: { '@type': 'Organization', name: 'Residential Realtors', logo: { '@type': 'ImageObject', url: opts.siteUrl + '/icons/app-180.png' } }, mainEntityOfPage: opts.siteUrl + '/landlord-guides/' + g.slug }] }, h);
  });

  // ---------- Free tools ----------
  // Rent increase calculator: the earliest date the new rent can start (two months' notice, and 52 weeks since the
  // tenancy began or the last increase), the size of the rise, and the ONS average for the borough and bedrooms.
  app.get('/landlord-tools/rent-increase-calculator', function (req, res) {
    const ons = opts.figures() || {}, list = opts.areas.map(function (a) { const g = (ons.boroughs || {})[a.gss] || {}; return { n: a.name, b: g.beds || {}, r: g.rent || null, m: g.bedsMonth || g.rentMonth || '' }; }).filter(function (x) { return x.r; }).sort(function (x, y) { return x.n.localeCompare(y.n); });
    const h = '<section class="ar-hero"><div class="wrap"><p class="ar-kick"><a href="/landlord-tools">Landlord tools</a></p><h1>Rent increase calculator</h1><p class="ar-lead">When can the new rent start, how big is the rise, and how does it compare with local rents? For assured periodic tenancies in England (section 13 notice).</p></div></section>' +
      '<section class="ar-main"><div class="wrap"><div class="ar-card tl-card"><form id="ric" class="tl-form" onsubmit="return false">' +
      '<label>Current rent (£ a month)<input type="number" min="1" step="1" id="ricNow" inputmode="numeric" required placeholder="e.g. 1800"></label>' +
      '<label>Proposed rent (£ a month)<input type="number" min="1" step="1" id="ricNew" inputmode="numeric" required placeholder="e.g. 1900"></label>' +
      '<label>Tenancy start date<input type="date" id="ricStart" required></label>' +
      '<label>Date of the last rent increase <small>(leave blank if none)</small><input type="date" id="ricLast"></label>' +
      '<label>Borough<select id="ricB"><option value="">—</option>' + list.map(function (x, i) { return '<option value="' + i + '">' + esc(x.n) + '</option>'; }).join('') + '</select></label>' +
      '<label>Bedrooms<select id="ricBeds"><option value="1">1</option><option value="2" selected>2</option><option value="3">3</option><option value="4">4+</option></select></label>' +
      '</form><div id="ricOut" class="tl-out" aria-live="polite"></div></div>' +
      '<p class="ar-src">Dates follow the section 13 rules: at least two months’ notice (monthly or weekly rent), and not within 52 weeks of the tenancy starting or the last increase. Local averages: ONS, all private rented homes in the borough. General guidance, not legal advice — read our <a href="/landlord-guides/how-to-raise-the-rent">guide to raising the rent</a>.</p></div></section>' +
      '<section class="ar-cta"><div class="wrap ar-cta-in"><div><h2>Want us to handle rent reviews?</h2><p>We track every review date, advise on the right rent and serve the notice for you.</p></div><div class="btns"><a class="btn red" href="/landlords#valuation">Free rental valuation →</a><a class="btn line" href="/landlords#services">Our services</a></div></div></section>' +
      '<script>(function(){var D=' + JSON.stringify(list).replace(/</g, '\\u003c') + ';var $=function(i){return document.getElementById(i)};' +
      'var f=function(d){return d.toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})};var g=function(n){return "£"+Math.round(n).toLocaleString("en-GB")};' +
      'function run(){var a=+$("ricNow").value,b=+$("ricNew").value,s=$("ricStart").value,l=$("ricLast").value,o=$("ricOut");if(!a||!b||!s){o.innerHTML="<p class=\\"tl-hint\\">Fill in the rents and the tenancy start date.</p>";return}' +
      'var base=new Date((l||s)+"T12:00:00");var y=new Date(base.getTime()+364*864e5);var t=new Date();t.setHours(12,0,0,0);var n=new Date(t);n.setMonth(n.getMonth()+2);var e=y>n?y:n;var serve=new Date(e);serve.setMonth(serve.getMonth()-2);if(serve<t)serve=t;' +
      'var p=(b-a)/a*100,h="<div class=\\"tl-res\\"><div><b>"+f(e)+"</b><span>earliest date the new rent can start</span></div><div><b>"+(p>=0?"+":"")+p.toFixed(1)+"%</b><span>"+(b>=a?"rise":"fall")+" of "+g(Math.abs(b-a))+" a month ("+g(Math.abs(b-a)*12)+" a year)</span></div></div>";' +
      'h+="<p>Serve the section 13 notice (Form 4A) by <b>"+f(serve)+"</b> for the new rent to start on "+f(e)+(y>n?" — the first date 52 weeks after "+(l?"the last increase":"the tenancy started"):"")+".</p>";' +
      'var x=D[$("ricB").value],k=$("ricBeds").value;if(x&&x.b&&x.b[k]){var av=x.b[k],d=(b-av)/av*100;h+="<p>The ONS average for a "+(k==="4"?"4+":k)+" bedroom home in "+x.n+" is <b>"+g(av)+" a month</b>"+(x.m?" ("+x.m+")":"")+". Your proposed rent is "+Math.abs(d).toFixed(0)+"% "+(d>=0?"above":"below")+" that average — homes differ, so compare with similar homes nearby.</p>"}' +
      'if(p>15)h+="<p class=\\"tl-warn\\">A large rise is more likely to be challenged at the tribunal, which sets the market rent. Make sure similar homes nearby are letting at this level.</p>";o.innerHTML=h}' +
      '["ricNow","ricNew","ricStart","ricLast","ricB","ricBeds"].forEach(function(i){$(i).addEventListener("input",run);$(i).addEventListener("change",run)});run()})();</script>';
    opts.send(req, res, { name: 'tools', stamp: 'ric1' + (list[0] ? list[0].m : ''), canon: '/landlord-tools/rent-increase-calculator', crumb: 'Landlord tools', crumbUrl: '/landlord-tools', crumb2: 'Rent increase calculator', title: 'Rent Increase Calculator for Landlords (Section 13) | Residential Realtors',
      desc: 'Free rent increase calculator: the earliest date a new rent can start under the section 13 rules, the size of the rise, and the ONS average rent in your borough.' }, h);
  });
  // Certificate due dates: gas every 12 months, EICR every 5 years, EPC every 10 years, with an .ics reminder.
  app.get('/landlord-tools/certificate-due-dates', function (req, res) {
    const h = '<section class="ar-hero"><div class="wrap"><p class="ar-kick"><a href="/landlord-tools">Landlord tools</a></p><h1>Certificate due-date checker</h1><p class="ar-lead">Enter when your last certificates were done to see when each is next due — and add reminders to your calendar.</p></div></section>' +
      '<section class="ar-main"><div class="wrap"><div class="ar-card tl-card"><form class="tl-form" onsubmit="return false">' +
      '<label>Last gas safety check<input type="date" id="cdGas"></label><label>Last EICR (electrical)<input type="date" id="cdEicr"></label><label>EPC issued<input type="date" id="cdEpc"></label></form>' +
      '<div id="cdOut" class="tl-out" aria-live="polite"></div></div>' +
      '<p class="ar-src">Gas safety: every 12 months. EICR: at least every five years (sooner if the report says so). EPC: valid for 10 years, and a rental normally needs E or above. See our <a href="/landlord-guides/landlord-safety-certificates">guide to landlord certificates</a>.</p></div></section>' +
      '<section class="ar-cta"><div class="wrap ar-cta-in"><div><h2>Something due soon?</h2><p>Book a Gas Safety certificate, EICR or EPC anywhere in London — online in minutes.</p></div><div class="btns"><a class="btn red" href="/book-certificate">Book a certificate →</a><a class="btn line" href="/landlords#valuation">Free rental valuation</a></div></div></section>' +
      '<script>(function(){var $=function(i){return document.getElementById(i)};var C=[["cdGas","Gas safety certificate",12,"/gas-safety-certificate"],["cdEicr","EICR (electrical)",60,"/eicr"],["cdEpc","EPC",120,"/epc"]];' +
      'var f=function(d){return d.toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})};var ics=function(d){return d.toISOString().slice(0,10).replace(/-/g,"")};' +
      'function run(){var t=new Date();t.setHours(12,0,0,0);var rows=[],ev=[];C.forEach(function(c){var v=$(c[0]).value;if(!v)return;var d=new Date(v+"T12:00:00");d.setMonth(d.getMonth()+c[2]);var left=Math.round((d-t)/864e5),st=left<0?"over":left<=60?"soon":"ok";' +
      'rows.push("<div class=\\"tl-row tl-"+st+"\\"><span><b>"+c[1]+"</b><small>"+(left<0?"Overdue since ":"Due ")+f(d)+(left>=0?" — in "+left+" days":"")+"</small></span><a class=\\"btn small "+(st==="ok"?"line":"red")+"\\" href=\\""+c[3]+"\\">Book</a></div>");' +
      'var r=new Date(d);r.setDate(r.getDate()-30);ev.push("BEGIN:VEVENT\\r\\nUID:"+c[0]+ics(d)+"@residentialrealtors.co.uk\\r\\nDTSTAMP:"+ics(t)+"T000000Z\\r\\nDTSTART;VALUE=DATE:"+ics(r)+"\\r\\nSUMMARY:"+c[1]+" due "+f(d)+"\\r\\nDESCRIPTION:Book at https://www.residentialrealtors.co.uk"+c[3]+"\\r\\nEND:VEVENT")});' +
      'var o=$("cdOut");if(!rows.length){o.innerHTML="<p class=\\"tl-hint\\">Enter at least one date.</p>";return}var cal="BEGIN:VCALENDAR\\r\\nVERSION:2.0\\r\\nPRODID:-//Residential Realtors//Certificates//EN\\r\\n"+ev.join("\\r\\n")+"\\r\\nEND:VCALENDAR";' +
      'o.innerHTML=rows.join("")+"<p><a class=\\"btn small line\\" download=\\"certificate-reminders.ics\\" href=\\"data:text/calendar;charset=utf-8,"+encodeURIComponent(cal)+"\\">📅 Add reminders to my calendar</a> <small class=\\"tl-hint\\">a reminder 30 days before each is due</small></p>"}' +
      '["cdGas","cdEicr","cdEpc"].forEach(function(i){$(i).addEventListener("input",run);$(i).addEventListener("change",run)});run()})();</script>';
    opts.send(req, res, { name: 'tools', stamp: 'cdd1', canon: '/landlord-tools/certificate-due-dates', crumb: 'Landlord tools', crumbUrl: '/landlord-tools', crumb2: 'Certificate due dates', title: 'Landlord Certificate Due-Date Checker | Residential Realtors',
      desc: 'When are your gas safety certificate, EICR and EPC next due? Free checker for landlords, with calendar reminders and online booking across London.' }, h);
  });
  return { urls: function () { return ['/landlord-guides'].concat(G.map(function (g) { return '/landlord-guides/' + g.slug; }), ['/landlord-tools/rent-increase-calculator', '/landlord-tools/certificate-due-dates']); } };
};
